/* 카테고리 */
DROP TABLE CATEGORY 
	CASCADE CONSTRAINTS;

/* 전문가 계정 */
DROP TABLE EXPERT 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 찜하기 */
DROP TABLE DIBS 
	CASCADE CONSTRAINTS;

/* 전문가 이력서 */
DROP TABLE RESUME 
	CASCADE CONSTRAINTS;

/* 쿠폰 */
DROP TABLE COUPON 
	CASCADE CONSTRAINTS;

/* 소유쿠폰 */
DROP TABLE GET_COUPON 
	CASCADE CONSTRAINTS;

/* 결제 */
DROP TABLE APPROVAL 
	CASCADE CONSTRAINTS;

/* 회원계정 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 이용후기 */
DROP TABLE REVIEW 
	CASCADE CONSTRAINTS;

/* 관리자 계정 */
DROP TABLE ADMIN 
	CASCADE CONSTRAINTS;

/* 견적서 요청 */
DROP TABLE REQUEST 
	CASCADE CONSTRAINTS;

/* Q&A 게시판 */
DROP TABLE QNA 
	CASCADE CONSTRAINTS;

/* 개발견적 */
DROP TABLE REQUEST_DEVELOP 
	CASCADE CONSTRAINTS;

/* 디자인견적 */
DROP TABLE REQUEST_DESIGN 
	CASCADE CONSTRAINTS;

/* 쪽지 */
DROP TABLE NOTE 
	CASCADE CONSTRAINTS;

/* 캐시충전 */
DROP TABLE CASH_CHARGE 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE COMMENT 
	CASCADE CONSTRAINTS;

/* 페이 */
DROP TABLE PAY 
	CASCADE CONSTRAINTS;

/* 게시판 타입 */
DROP TABLE BOARD_TYPE 
	CASCADE CONSTRAINTS;

/* 자격증 */
DROP TABLE LICENSE 
	CASCADE CONSTRAINTS;

/* 경력사항 */
DROP TABLE CAREER 
	CASCADE CONSTRAINTS;

/* 견적요청문답 */
DROP TABLE REQUEST_QNA 
	CASCADE CONSTRAINTS;

/* 카테고리 */
CREATE TABLE CATEGORY (
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	MAIN VARCHAR2(30) NOT NULL, /* 메인카테고리(개발/디자인) */
	DETAIL VARCHAR2(30) NOT NULL /* 세부카테고리 */
);

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		CATEGORY_NO ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CATEGORY_NO
		);

/* 전문가 계정 */
CREATE TABLE EXPERT (
	EXPERT_NO NUMBER NOT NULL, /* 개발자 번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	PWD VARCHAR2(30) NOT NULL, /* 비밀번호 */
	ADDRESS1 VARCHAR2(30) NOT NULL, /* 주소 */
	ADDRESS2 VARCHAR2(50) NOT NULL, /* 상세주소 */
	ZIPCODE VARCHAR2(20) NOT NULL, /* 우편번호 */
	REGDATE DATE NOT NULL, /* 가입일 */
	HP1 NUMBER NOT NULL, /* 번호1 */
	HP2 NUMBER NOT NULL, /* 번호2 */
	HP3 NUMBER NOT NULL, /* 번호3 */
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	RESUME_CODE NUMBER NOT NULL /* 이력서 코드 */
);

CREATE UNIQUE INDEX PK_EXPERT
	ON EXPERT (
		EXPERT_NO ASC
	);

ALTER TABLE EXPERT
	ADD
		CONSTRAINT PK_EXPERT
		PRIMARY KEY (
			EXPERT_NO
		);

/* 게시판 */
CREATE TABLE BOARD (
	NO NUMBER NOT NULL, /* 게시판 번호 */
	BOARD_TYPE NUMBER NOT NULL, /* 게시판 타입 번호 */
	TITLE VARCHAR2(50) NOT NULL, /* 제목 */
	WRITER VARCHAR2(30), /* 작성자 */
	CONTENT CLOB NOT NULL, /* 내용 */
	EMAIL VARCHAR2(50) NOT NULL, /* 이메일 */
	READCOUNT NUMBER NOT NULL, /* 조회수 */
	DELFLAG VARCHAR2(1) DEFAULT N NOT NULL, /* 삭제플래그 */
	FILE_NAME VARCHAR2(50), /* 파일명 */
	FILE_SIZE NUMBER, /* 파일사이즈 */
	ORIGINALFILENAME VARCHAR2(50), /* 원본파일명 */
	DOWNCOUNT NUMBER NOT NULL, /* 다운로드수 */
	REGDATE DATE DEFAULT sysdate NOT NULL /* 작성일 */
);

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		NO ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			NO
		);

/* 찜하기 */
CREATE TABLE DIBS (
	DIBS_NO NUMBER NOT NULL, /* 찜하기 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	EXPERT_NO NUMBER NOT NULL /* 개발자 번호 */
);

CREATE UNIQUE INDEX PK_DIBS
	ON DIBS (
		DIBS_NO ASC
	);

ALTER TABLE DIBS
	ADD
		CONSTRAINT PK_DIBS
		PRIMARY KEY (
			DIBS_NO
		);

/* 전문가 이력서 */
CREATE TABLE RESUME (
	RESUME_CODE NUMBER NOT NULL, /* 이력서 코드 */
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	EXPERT_NO NUMBER, /* 개발자 번호 */
	INTRODUCE CLOB NOT NULL, /* 자기소개 */
	EXPERTISE VARCHAR2(40) NOT NULL, /* 전문분야 */
	SKILL VARCHAR2(50) NOT NULL, /* 보유기술 */
	EDUCATION VARCHAR2(50) NOT NULL, /* 학력 */
	LICENSE CLOB NOT NULL, /* 자격증 */
	CAREER CLOB NOT NULL, /* 경력사항 */
	ETC CLOB NOT NULL /* 기타 */
);

CREATE UNIQUE INDEX PK_RESUME
	ON RESUME (
		RESUME_CODE ASC
	);

ALTER TABLE RESUME
	ADD
		CONSTRAINT PK_RESUME
		PRIMARY KEY (
			RESUME_CODE
		);

/* 쿠폰 */
CREATE TABLE COUPON (
	COUPON_NO NUMBER NOT NULL, /* 쿠폰번호 */
	NAME VARCHAR(50) NOT NULL, /* 쿠폰이름 */
	DISCOUNT NUMBER NOT NULL, /* 할인금액 */
	EXPIRE_DATE DATE NOT NULL /* 사용기한 */
);

CREATE UNIQUE INDEX PK_COUPON
	ON COUPON (
		COUPON_NO ASC
	);

ALTER TABLE COUPON
	ADD
		CONSTRAINT PK_COUPON
		PRIMARY KEY (
			COUPON_NO
		);

/* 소유쿠폰 */
CREATE TABLE GET_COUPON (
	SERIAL_NO NUMBER NOT NULL, /* 발급번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	COUPON_NO NUMBER /* 쿠폰번호 */
);

CREATE UNIQUE INDEX PK_GET_COUPON
	ON GET_COUPON (
		SERIAL_NO ASC
	);

ALTER TABLE GET_COUPON
	ADD
		CONSTRAINT PK_GET_COUPON
		PRIMARY KEY (
			SERIAL_NO
		);

/* 결제 */
CREATE TABLE APPROVAL (
	APPROVAL_NO NUMBER NOT NULL, /* 결제 번호 */
	PAY_INFO VARCHAR2(30) NOT NULL, /* 결제정보 */
	METHOD VARCHAR2(20) NOT NULL, /* 결제 수단 */
	PROGRESS VARCHAR2(20) NOT NULL, /* 진행상태 */
	DISCOUNT NUMBER NOT NULL, /* 할인금액 */
	PAYMENT NUMBER NOT NULL, /* 결제 금액 */
	PAY_DATE DATE NOT NULL, /* 결제일 */
	REQUEST_NO NUMBER /* 견적서 번호 */
);

CREATE UNIQUE INDEX PK_APPROVAL
	ON APPROVAL (
		APPROVAL_NO ASC
	);

ALTER TABLE APPROVAL
	ADD
		CONSTRAINT PK_APPROVAL
		PRIMARY KEY (
			APPROVAL_NO
		);

/* 회원계정 */
CREATE TABLE MEMBER (
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	NAME VARCHAR2(20) NOT NULL, /* 이름 */
	EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	PWD VARCHAR2(30) NOT NULL, /* 비밀번호 */
	REGDATE DATE DEFAULT sysdate NOT NULL, /* 가입일 */
	ADDRESS1 VARCHAR2(30), /* 주소 */
	ADDRESS2 VARCHAR2(50), /* 상세주소 */
	ZIPCODE VARCHAR2(20) /* 우편번호 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		MEMBER_NO ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			MEMBER_NO
		);

/* 이용후기 */
CREATE TABLE REVIEW (
	REVIEW_NO NUMBER NOT NULL, /* 이용후기 번호 */
	EXPERT_NO NUMBER NOT NULL, /* 전문가 번호 */
	TITLE VARCHAR(50) NOT NULL, /* 제목 */
	CONTENT CLOB NOT NULL, /* 내용 */
	READCOUNT NUMBER NOT NULL, /* 조회수 */
	DELFLAG VARCHAR(1) DEFAULT N NOT NULL, /* 삭제플래그 */
	FILE_NAME VARCHAR(50), /* 파일명 */
	FILE_SIZE NUMBER, /* 파일사이즈 */
	ORIGINALFILENAME VARCHAR(50), /* 원본파일명 */
	DOWNCOUNT NUMBER NOT NULL, /* 다운로드수 */
	REGDATE DATE DEFAULT sysdate NOT NULL, /* 작성일 */
	SCORE VARCHAR2(10) NOT NULL /* 별점 */
);

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		REVIEW_NO ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			REVIEW_NO
		);

/* 관리자 계정 */
CREATE TABLE ADMIN (
	ADMIN_NO NUMBER NOT NULL, /* 관리자 번호 */
	NAME VARCHAR2(20) NOT NULL, /* 관리자명 */
	EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	PWD VARCHAR2(30) NOT NULL /* 비밀번호 */
);

CREATE UNIQUE INDEX PK_ADMIN
	ON ADMIN (
		ADMIN_NO ASC
	);

ALTER TABLE ADMIN
	ADD
		CONSTRAINT PK_ADMIN
		PRIMARY KEY (
			ADMIN_NO
		);

/* 견적서 요청 */
CREATE TABLE REQUEST (
	REQUEST_NO NUMBER NOT NULL, /* 견적서 번호 */
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	EXPERT_NO NUMBER, /* 개발자 번호 */
	REQUEST_DESIGN_NO NUMBER, /* 디자인견적번호 */
	REQUEST_DEVELOP_NO NUMBER, /* 개발견적번호 */
	SEND_TIME DATE NOT NULL, /* 요청일자 */
	MATCH VARCHAR2(1) DEFAULT N NOT NULL /* 매칭여부 */
);

CREATE UNIQUE INDEX PK_REQUEST
	ON REQUEST (
		REQUEST_NO ASC
	);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT PK_REQUEST
		PRIMARY KEY (
			REQUEST_NO
		);

/* Q&A 게시판 */
CREATE TABLE QNA (
	QNA_NO NUMBER NOT NULL, /* Q&A 번호 */
	ADMIN_NO NUMBER NOT NULL, /* 관리자 번호 */
	TITLE VARCHAR(50) NOT NULL, /* 제목 */
	CONTENT CLOB NOT NULL, /* 내용 */
	READCOUNT NUMBER NOT NULL, /* 조회수 */
	REGDATE DATE DEFAULT sysdate NOT NULL /* 작성일 */
);

CREATE UNIQUE INDEX PK_QNA
	ON QNA (
		QNA_NO ASC
	);

ALTER TABLE QNA
	ADD
		CONSTRAINT PK_QNA
		PRIMARY KEY (
			QNA_NO
		);

/* 개발견적 */
CREATE TABLE REQUEST_DEVELOP (
	REQUEST_DEVELOP_NO NUMBER NOT NULL, /* 개발견적번호 */
	PLATFORM VARCHAR2(60) NOT NULL, /* 개발플랫폼 */
	TYPE VARCHAR2(60) NOT NULL, /* 개발종류 */
	CAREER VARCHAR2(30) NOT NULL, /* 원하는 숙련도(연차) */
	STEP VARCHAR2(30) NOT NULL, /* 기획단계 */
	REFERENCE CLOB, /* 참고사항 */
	DEADLINE VARCHAR2(80) NOT NULL, /* 작업완료기간 */
	WORKTYPE VARCHAR2(80) NOT NULL, /* 업무진행방식 */
	LOCATION1 VARCHAR2(30) NOT NULL, /* 지역1 */
	LOCATION2 VARCHAR2(30) NOT NULL /* 지역2 */
);

CREATE UNIQUE INDEX PK_REQUEST_DEVELOP
	ON REQUEST_DEVELOP (
		REQUEST_DEVELOP_NO ASC
	);

ALTER TABLE REQUEST_DEVELOP
	ADD
		CONSTRAINT PK_REQUEST_DEVELOP
		PRIMARY KEY (
			REQUEST_DEVELOP_NO
		);

/* 디자인견적 */
CREATE TABLE REQUEST_DESIGN (
	REQUEST_DESIGN_NO NUMBER NOT NULL, /* 디자인견적번호 */
	TYPE VARCHAR2(80) NOT NULL, /* 페이지종류 */
	RANGE VARCHAR2(50) NOT NULL, /* 디자인범위 */
	SCALE VARCHAR2(80) NOT NULL, /* 작업분량 */
	DEVELOP VARCHAR2(80) NOT NULL, /* 개발추가여부 */
	DEADLINE VARCHAR2(80) NOT NULL, /* 작업완료기간 */
	LOCATION1 VARCHAR2(30) NOT NULL, /* 회원지역1 */
	LOCATION2 VARCHAR2(30) NOT NULL, /* 회원지역2 */
	QUESTION CLOB /* 디자인 관련 문의사항 */
);

CREATE UNIQUE INDEX PK_REQUEST_DESIGN
	ON REQUEST_DESIGN (
		REQUEST_DESIGN_NO ASC
	);

ALTER TABLE REQUEST_DESIGN
	ADD
		CONSTRAINT PK_REQUEST_DESIGN
		PRIMARY KEY (
			REQUEST_DESIGN_NO
		);

/* 쪽지 */
CREATE TABLE NOTE (
	SEND_NO NUMBER NOT NULL, /* 쪽지 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	TITLE VARCHAR2(30) NOT NULL, /* 제목 */
	CONTENT CLOB NOT NULL, /* 내용 */
	SEND_TIME DATE NOT NULL /* 보낸시간 */
);

CREATE UNIQUE INDEX PK_NOTE
	ON NOTE (
		SEND_NO ASC
	);

ALTER TABLE NOTE
	ADD
		CONSTRAINT PK_NOTE
		PRIMARY KEY (
			SEND_NO
		);

/* 캐시충전 */
CREATE TABLE CASH_CHARGE (
	CASH_CHARGE_NO NUMBER NOT NULL, /* 캐시 충전 번호 */
	CHARGE_PAY NUMBER NOT NULL, /* 캐시 충전 금액 */
	REGDATE DATE DEFAULT sysdate NOT NULL, /* 충전일 */
	BALANCE NUMBER DEFAULT BALANCE > 0 NOT NULL, /* 잔액 */
	MEMBER_NO NUMBER NOT NULL /* 회원 번호 */
);

CREATE UNIQUE INDEX PK_CASH_CHARGE
	ON CASH_CHARGE (
		CASH_CHARGE_NO ASC
	);

ALTER TABLE CASH_CHARGE
	ADD
		CONSTRAINT PK_CASH_CHARGE
		PRIMARY KEY (
			CASH_CHARGE_NO
		);

/* 댓글 */
CREATE TABLE COMMENT (
	COMMENT_NO NUMBER NOT NULL, /* 댓글 번호 */
	NO NUMBER NOT NULL, /* 게시판 번호 */
	REVIEW_NO NUMBER NOT NULL, /* 이용후기 번호 */
	CONTENT CLOB NOT NULL, /* 내용 */
	REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 등록일자 */
	GROUP_NO NUMBER, /* 그룹번호 */
	SORT_NO NUMBER, /* 정렬번호 */
	STEP NUMBER, /* 단계 */
	DELFLAG VARCHAR2(1) DEFAULT N NOT NULL /* 삭제여부 */
);

CREATE UNIQUE INDEX PK_COMMENT
	ON COMMENT (
		COMMENT_NO ASC,
		NO ASC,
		REVIEW_NO ASC
	);

ALTER TABLE COMMENT
	ADD
		CONSTRAINT PK_COMMENT
		PRIMARY KEY (
			COMMENT_NO,
			NO,
			REVIEW_NO
		);

/* 페이 */
CREATE TABLE PAY (
	PAY_NO NUMBER NOT NULL, /* 페이 번호 */
	EXPERT_NO NUMBER NOT NULL, /* 전문가 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	DATE DATE NOT NULL, /* 의뢰일 */
	PRICE NUMBER NOT NULL, /* 서비스비용 */
	TOTAL_PRICE NUMBER NOT NULL /* 총정산금액 */
);

CREATE UNIQUE INDEX PK_PAY
	ON PAY (
		PAY_NO ASC
	);

ALTER TABLE PAY
	ADD
		CONSTRAINT PK_PAY
		PRIMARY KEY (
			PAY_NO
		);

/* 게시판 타입 */
CREATE TABLE BOARD_TYPE (
	BOARDTYPE_NO NUMBER NOT NULL, /* 게시판 타입 번호 */
	BOARD_NAME VARCHAR2(30) /* 게시판 이름 */
);

CREATE UNIQUE INDEX PK_BOARD_TYPE
	ON BOARD_TYPE (
		BOARDTYPE_NO ASC
	);

ALTER TABLE BOARD_TYPE
	ADD
		CONSTRAINT PK_BOARD_TYPE
		PRIMARY KEY (
			BOARDTYPE_NO
		);

/* 자격증 */
CREATE TABLE LICENSE (
	LICENSE_NO NUMBER NOT NULL, /* 구분코드 */
	LICENSE_NAME VARCHAR2(80), /* 자격증 */
	LICENSE_ISSUELACE VARCHAR2(80), /* 발행처 */
	RESUME_CODE NUMBER /* 이력서 코드 */
);

CREATE UNIQUE INDEX PK_LICENSE
	ON LICENSE (
		LICENSE_NO ASC
	);

ALTER TABLE LICENSE
	ADD
		CONSTRAINT PK_LICENSE
		PRIMARY KEY (
			LICENSE_NO
		);

/* 경력사항 */
CREATE TABLE CAREER (
	CAREER_NO NUMBER NOT NULL, /* 구분코드 */
	CAREER_CORP VARCHAR2(80) NOT NULL, /* 회사 */
	CAREER_STARTDATE VARCHAR2(80), /* 근무기간시작 */
	CAREER_ENDDATE VARCHAR2(80), /* 근무기간 끝 */
	CAREER_WORK VARCHAR2(80), /* 담당업무 */
	RESUME_CODE NUMBER /* 이력서 코드 */
);

CREATE UNIQUE INDEX PK_CAREER
	ON CAREER (
		CAREER_NO ASC
	);

ALTER TABLE CAREER
	ADD
		CONSTRAINT PK_CAREER
		PRIMARY KEY (
			CAREER_NO
		);

/* 견적요청문답 */
CREATE TABLE REQUEST_QNA (
	QNA_NO NUMBER NOT NULL, /* 문답번호 */
	CATEGORY_NO NUMBER NOT NULL, /* 카테고리 번호 */
	REQUEST_QUESTION VARCHAR2(80) NOT NULL, /* 질문 */
	REQUEST_ANSWER VARCHAR2(80) NOT NULL /* 답 */
);

CREATE UNIQUE INDEX PK_REQUEST_QNA
	ON REQUEST_QNA (
		QNA_NO ASC
	);

ALTER TABLE REQUEST_QNA
	ADD
		CONSTRAINT PK_REQUEST_QNA
		PRIMARY KEY (
			QNA_NO
		);

ALTER TABLE EXPERT
	ADD
		CONSTRAINT FK_RESUME_TO_EXPERT
		FOREIGN KEY (
			RESUME_CODE
		)
		REFERENCES RESUME (
			RESUME_CODE
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_BOARD_TYPE_TO_BOARD
		FOREIGN KEY (
			BOARD_TYPE
		)
		REFERENCES BOARD_TYPE (
			BOARDTYPE_NO
		);

ALTER TABLE DIBS
	ADD
		CONSTRAINT FK_MEMBER_TO_DIBS
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE DIBS
	ADD
		CONSTRAINT FK_EXPERT_TO_DIBS
		FOREIGN KEY (
			EXPERT_NO
		)
		REFERENCES EXPERT (
			EXPERT_NO
		);

ALTER TABLE RESUME
	ADD
		CONSTRAINT FK_CATEGORY_TO_RESUME
		FOREIGN KEY (
			CATEGORY_NO
		)
		REFERENCES CATEGORY (
			CATEGORY_NO
		);

ALTER TABLE RESUME
	ADD
		CONSTRAINT FK_EXPERT_TO_RESUME
		FOREIGN KEY (
			EXPERT_NO
		)
		REFERENCES EXPERT (
			EXPERT_NO
		);

ALTER TABLE GET_COUPON
	ADD
		CONSTRAINT FK_COUPON_TO_GET_COUPON
		FOREIGN KEY (
			COUPON_NO
		)
		REFERENCES COUPON (
			COUPON_NO
		);

ALTER TABLE GET_COUPON
	ADD
		CONSTRAINT FK_MEMBER_TO_GET_COUPON
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE APPROVAL
	ADD
		CONSTRAINT FK_REQUEST_TO_APPROVAL
		FOREIGN KEY (
			REQUEST_NO
		)
		REFERENCES REQUEST (
			REQUEST_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_EXPERT_TO_REVIEW
		FOREIGN KEY (
			EXPERT_NO
		)
		REFERENCES EXPERT (
			EXPERT_NO
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_CATEGORY_TO_REQUEST
		FOREIGN KEY (
			CATEGORY_NO
		)
		REFERENCES CATEGORY (
			CATEGORY_NO
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_MEMBER_TO_REQUEST
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_EXPERT_TO_REQUEST
		FOREIGN KEY (
			EXPERT_NO
		)
		REFERENCES EXPERT (
			EXPERT_NO
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_REQUEST_DESIGN_TO_REQUEST
		FOREIGN KEY (
			REQUEST_DESIGN_NO
		)
		REFERENCES REQUEST_DESIGN (
			REQUEST_DESIGN_NO
		);

ALTER TABLE REQUEST
	ADD
		CONSTRAINT FK_REQUEST_DEVELOP_TO_REQUEST
		FOREIGN KEY (
			REQUEST_DEVELOP_NO
		)
		REFERENCES REQUEST_DEVELOP (
			REQUEST_DEVELOP_NO
		);

ALTER TABLE QNA
	ADD
		CONSTRAINT FK_ADMIN_TO_QNA
		FOREIGN KEY (
			ADMIN_NO
		)
		REFERENCES ADMIN (
			ADMIN_NO
		);

ALTER TABLE NOTE
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTE
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE CASH_CHARGE
	ADD
		CONSTRAINT FK_MEMBER_TO_CASH_CHARGE
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE COMMENT
	ADD
		CONSTRAINT FK_BOARD_TO_COMMENT
		FOREIGN KEY (
			NO
		)
		REFERENCES BOARD (
			NO
		);

ALTER TABLE COMMENT
	ADD
		CONSTRAINT FK_REVIEW_TO_COMMENT
		FOREIGN KEY (
			REVIEW_NO
		)
		REFERENCES REVIEW (
			REVIEW_NO
		);

ALTER TABLE PAY
	ADD
		CONSTRAINT FK_MEMBER_TO_PAY
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE PAY
	ADD
		CONSTRAINT FK_CATEGORY_TO_PAY
		FOREIGN KEY (
			CATEGORY_NO
		)
		REFERENCES CATEGORY (
			CATEGORY_NO
		);

ALTER TABLE PAY
	ADD
		CONSTRAINT FK_EXPERT_TO_PAY
		FOREIGN KEY (
			EXPERT_NO
		)
		REFERENCES EXPERT (
			EXPERT_NO
		);

ALTER TABLE LICENSE
	ADD
		CONSTRAINT FK_RESUME_TO_LICENSE
		FOREIGN KEY (
			RESUME_CODE
		)
		REFERENCES RESUME (
			RESUME_CODE
		);

ALTER TABLE CAREER
	ADD
		CONSTRAINT FK_RESUME_TO_CAREER
		FOREIGN KEY (
			RESUME_CODE
		)
		REFERENCES RESUME (
			RESUME_CODE
		);

ALTER TABLE REQUEST_QNA
	ADD
		CONSTRAINT FK_CATEGORY_TO_REQUEST_QNA
		FOREIGN KEY (
			CATEGORY_NO
		)
		REFERENCES CATEGORY (
			CATEGORY_NO
		);